### ISSUE TITLE
Rehearse does not work with CglPreProcess

### ISSUE THREAD

**Issue by hacst** [coin-or/Rehearse#4]
When using CglPreProcess to pre-process on a model description like so:
```
  CglPreProcess process;
  OsiSolverInterface* preProcessedSolver = process.preProcess(solver, false); 
```
The pre-processed model might have less/other columns than the original one (e.g. one was redundant and is dropped). As far as I can tell rehearse internally identifies results by their column id. This fails in such cases. In my specific case I'm looking at the x0 column was dropped and x1, x2 became x0, x1.

Is there a good way to handle this that I missed? If not having rehearse be capable to handle such changes would be helpful.

**Comment by Celebio** [comment]
Hi,
Could you provide a compilable example?

Thanks,
Onur

**Comment by Celebio** [comment]
No answer. Closing issue
