### ISSUE TITLE
Defining Rehearse environment in C++ oriented Object

### ISSUE THREAD

**Issue by yacinsky** [coin-or/Rehearse#5]
Hi,
I am working with rehearse in order to eliminate ,in my plateform, the concert (Cplex) dependencies.  So i have some error when i define the reheahse/coin environement,

OsiClpSolverInterface coinSolver;
this->coinSolver = coinSolver;
this->coinModel=CelModel(this->coinSolver); ==> (error: No operator "=" corresponds to these operands).

Thanks for help

**Comment by Celebio** [comment]
Hi,
CelModel is not a subclass of CoinModel. You should use model.builderToSolver(). You can check [the examples in the test file](https://github.com/coin-or/Rehearse/blob/master/Rehearse/tests/testRehearse.cpp#L46).

Regards,
Onur
