### ISSUE TITLE
non-respected constraints

### ISSUE THREAD

**Issue by Marcus981** [coin-or/Rehearse#6]
Hello, thanks for the good job you have done with this project.
I have some problems when I try to run my code, which is supposed to solve LP problems.
the solver basically does not respects constraints, for example, when I set a CelboolArray, which I think is supposed to be of integers ( 0 and 1 ), in my solution I get values like 0.6666 or 0.2, which are not integers.
Another problem that I got is that despite the fact I set all the variables of a CelBoolArray between 0 and 1, I got one variable = 2. the code compile and run smoothly, sometimes for some problems I get the expected results some other times I dont.

**Comment by Celebio** [comment]
Hi @Marcus981 ,
If you want to constraint some variables to be integers (or booleans), you need to use CbcSolver.

Is it the case?

If not, you can look at the [this example](https://github.com/coin-or/Rehearse/blob/master/Rehearse/tests/testRehearse.cpp#L131)

Cbc is a branch and bound ILP solver that uses Clp at each node.
Clp can also give you integer solutions time to time, either by chance or because your constraint matrix is totally unimodular.

**Comment by Marcus981** [comment]
thanks for your fast answers and sorry for bothering u again.
I changed this line in my code

//OsiClpSolverInterface * solver = new OsiClpSolverInterface();

with this

OsiCbcSolverInterface * solver = new OsiCbcSolverInterface();

but I'm quite lost, since I'm still getting unauthorized values.
this is what I get:

![screenshot at 2017-09-28 01 11 04](https://user-images.githubusercontent.com/32345094/30942345-bfe2ddbc-a3ea-11e7-81be-90a1b94210e5.png)

and here y_(60)^1 = 2

![screenshot at 2017-09-28 01 18 28](https://user-images.githubusercontent.com/32345094/30942377-05b37ba8-a3eb-11e7-95fa-27d4956e686d.png)

Can you tell me how to set the cbc solver ? I checked within the tests of the projects and there is only example with a cbc solver, and I think i'm doing like that.

**Comment by Marcus981** [comment]
nevermind my last message, I solved the problem. I didnt realized that the instance of my problem was infeasible, my bad, thanks.

**Comment by Celebio** [comment]
That might not be the only issue you had. Using `OsiCbcSolverInterface` instead of `OsiClpSolverInterface` is not enough. Make sure to use cbcModel.branchAndBound(); as in the examples.
Good luck :)

**Comment by knavely** [comment]
Hi, I have been experiencing a similar issue. I am trying to use the OsiCbcSolverInterface, yet sometimes i seem to end up with non integer solutions. Would greatly appreciate any insights. Here is exactly what I am doing:

  OsiCbcSolverInterface solver;
  CelModel model(solver);
  CelVariableArray<CelIntVar> x;
  //CelBoolVarArray x;
  x.multiDimensionResize(1,n);
  CelExpression objective;
  for(int i = 0; i < n; ++i) {
    objective += x[i];
  }
  model.setObjective(objective);
  //add set constraints
  for(int i = 1; i <= map.size(); ++i) {
    CelExpression setConstraint;
    std::vector<int> contains;  
    for(int j = 0; j < sets.size(); ++j) {
      if(std::find(sets[j].begin(), sets[j].end(),i) != sets[j].end()) {
        contains.push_back(j);
      }
    }
    for(auto ix: contains) {
      setConstraint += x[ix];
    }
    model.addConstraint(1 <= setConstraint);
  }
  for(int i = 0; i < n; ++i) {
    model.addConstraint(0 <= x[i]);
    model.addConstraint(x[i] <= 1);
  }
  solver.setObjSense(1.0);
  model.builderToSolver();
  //solver.setLogLevel(0);
  solver.initialSolve();
  solver.branchAndBound();

  printf("number of variables %i \n",n);
  std::vector<double> solution(n) ;
  for(int i = 0; i < n; ++i) {
    double xi = model.getSolutionValue(x[i]);
    printf("Solution for x_%i : %g\n", i, xi);
    solution[i] = xi;
  }
